/* This file was generated by SableCC (http://www.sablecc.org/). */

package portugol.node;

import java.util.*;
import portugol.analysis.*;

@SuppressWarnings("nls")
public final class AAvalieComando extends PComando
{
    private PExp _exp_;
    private final LinkedList<PCasoOpcao> _casoOpcao_ = new LinkedList<PCasoOpcao>();
    private PPadrao _padrao_;

    public AAvalieComando()
    {
        // Constructor
    }

    public AAvalieComando(
        @SuppressWarnings("hiding") PExp _exp_,
        @SuppressWarnings("hiding") List<?> _casoOpcao_,
        @SuppressWarnings("hiding") PPadrao _padrao_)
    {
        // Constructor
        setExp(_exp_);

        setCasoOpcao(_casoOpcao_);

        setPadrao(_padrao_);

    }

    @Override
    public Object clone()
    {
        return new AAvalieComando(
            cloneNode(this._exp_),
            cloneList(this._casoOpcao_),
            cloneNode(this._padrao_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAvalieComando(this);
    }

    public PExp getExp()
    {
        return this._exp_;
    }

    public void setExp(PExp node)
    {
        if(this._exp_ != null)
        {
            this._exp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exp_ = node;
    }

    public LinkedList<PCasoOpcao> getCasoOpcao()
    {
        return this._casoOpcao_;
    }

    public void setCasoOpcao(List<?> list)
    {
        for(PCasoOpcao e : this._casoOpcao_)
        {
            e.parent(null);
        }
        this._casoOpcao_.clear();

        for(Object obj_e : list)
        {
            PCasoOpcao e = (PCasoOpcao) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._casoOpcao_.add(e);
        }
    }

    public PPadrao getPadrao()
    {
        return this._padrao_;
    }

    public void setPadrao(PPadrao node)
    {
        if(this._padrao_ != null)
        {
            this._padrao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._padrao_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._exp_)
            + toString(this._casoOpcao_)
            + toString(this._padrao_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._exp_ == child)
        {
            this._exp_ = null;
            return;
        }

        if(this._casoOpcao_.remove(child))
        {
            return;
        }

        if(this._padrao_ == child)
        {
            this._padrao_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._exp_ == oldChild)
        {
            setExp((PExp) newChild);
            return;
        }

        for(ListIterator<PCasoOpcao> i = this._casoOpcao_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PCasoOpcao) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        if(this._padrao_ == oldChild)
        {
            setPadrao((PPadrao) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
