/* This file was generated by SableCC (http://www.sablecc.org/). */

package portugol.node;

import java.util.*;
import portugol.analysis.*;

@SuppressWarnings("nls")
public final class ACasoOpcao extends PCasoOpcao
{
    private TCaso _caso_;
    private PValor _valor_;
    private TDoisPts _doisPts_;
    private final LinkedList<PComandoPtVirg> _comandoPtVirg_ = new LinkedList<PComandoPtVirg>();

    public ACasoOpcao()
    {
        // Constructor
    }

    public ACasoOpcao(
        @SuppressWarnings("hiding") TCaso _caso_,
        @SuppressWarnings("hiding") PValor _valor_,
        @SuppressWarnings("hiding") TDoisPts _doisPts_,
        @SuppressWarnings("hiding") List<?> _comandoPtVirg_)
    {
        // Constructor
        setCaso(_caso_);

        setValor(_valor_);

        setDoisPts(_doisPts_);

        setComandoPtVirg(_comandoPtVirg_);

    }

    @Override
    public Object clone()
    {
        return new ACasoOpcao(
            cloneNode(this._caso_),
            cloneNode(this._valor_),
            cloneNode(this._doisPts_),
            cloneList(this._comandoPtVirg_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseACasoOpcao(this);
    }

    public TCaso getCaso()
    {
        return this._caso_;
    }

    public void setCaso(TCaso node)
    {
        if(this._caso_ != null)
        {
            this._caso_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._caso_ = node;
    }

    public PValor getValor()
    {
        return this._valor_;
    }

    public void setValor(PValor node)
    {
        if(this._valor_ != null)
        {
            this._valor_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._valor_ = node;
    }

    public TDoisPts getDoisPts()
    {
        return this._doisPts_;
    }

    public void setDoisPts(TDoisPts node)
    {
        if(this._doisPts_ != null)
        {
            this._doisPts_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._doisPts_ = node;
    }

    public LinkedList<PComandoPtVirg> getComandoPtVirg()
    {
        return this._comandoPtVirg_;
    }

    public void setComandoPtVirg(List<?> list)
    {
        for(PComandoPtVirg e : this._comandoPtVirg_)
        {
            e.parent(null);
        }
        this._comandoPtVirg_.clear();

        for(Object obj_e : list)
        {
            PComandoPtVirg e = (PComandoPtVirg) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._comandoPtVirg_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._caso_)
            + toString(this._valor_)
            + toString(this._doisPts_)
            + toString(this._comandoPtVirg_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._caso_ == child)
        {
            this._caso_ = null;
            return;
        }

        if(this._valor_ == child)
        {
            this._valor_ = null;
            return;
        }

        if(this._doisPts_ == child)
        {
            this._doisPts_ = null;
            return;
        }

        if(this._comandoPtVirg_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._caso_ == oldChild)
        {
            setCaso((TCaso) newChild);
            return;
        }

        if(this._valor_ == oldChild)
        {
            setValor((PValor) newChild);
            return;
        }

        if(this._doisPts_ == oldChild)
        {
            setDoisPts((TDoisPts) newChild);
            return;
        }

        for(ListIterator<PComandoPtVirg> i = this._comandoPtVirg_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PComandoPtVirg) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
