/* This file was generated by SableCC (http://www.sablecc.org/). */

package portugol.node;

import portugol.analysis.*;

@SuppressWarnings("nls")
public final class AEExpE extends PExpE
{
    private PExpE _expE_;
    private TE _e_;
    private PExpIgual _expIgual_;

    public AEExpE()
    {
        // Constructor
    }

    public AEExpE(
        @SuppressWarnings("hiding") PExpE _expE_,
        @SuppressWarnings("hiding") TE _e_,
        @SuppressWarnings("hiding") PExpIgual _expIgual_)
    {
        // Constructor
        setExpE(_expE_);

        setE(_e_);

        setExpIgual(_expIgual_);

    }

    @Override
    public Object clone()
    {
        return new AEExpE(
            cloneNode(this._expE_),
            cloneNode(this._e_),
            cloneNode(this._expIgual_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAEExpE(this);
    }

    public PExpE getExpE()
    {
        return this._expE_;
    }

    public void setExpE(PExpE node)
    {
        if(this._expE_ != null)
        {
            this._expE_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expE_ = node;
    }

    public TE getE()
    {
        return this._e_;
    }

    public void setE(TE node)
    {
        if(this._e_ != null)
        {
            this._e_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._e_ = node;
    }

    public PExpIgual getExpIgual()
    {
        return this._expIgual_;
    }

    public void setExpIgual(PExpIgual node)
    {
        if(this._expIgual_ != null)
        {
            this._expIgual_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expIgual_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expE_)
            + toString(this._e_)
            + toString(this._expIgual_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expE_ == child)
        {
            this._expE_ = null;
            return;
        }

        if(this._e_ == child)
        {
            this._e_ = null;
            return;
        }

        if(this._expIgual_ == child)
        {
            this._expIgual_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expE_ == oldChild)
        {
            setExpE((PExpE) newChild);
            return;
        }

        if(this._e_ == oldChild)
        {
            setE((TE) newChild);
            return;
        }

        if(this._expIgual_ == oldChild)
        {
            setExpIgual((PExpIgual) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
