/* This file was generated by SableCC (http://www.sablecc.org/). */

package portugol.node;

import java.util.*;
import portugol.analysis.*;

@SuppressWarnings("nls")
public final class AElseParte extends PElseParte
{
    private TSenao _senao_;
    private final LinkedList<PComandoPtVirg> _comandoPtVirg_ = new LinkedList<PComandoPtVirg>();

    public AElseParte()
    {
        // Constructor
    }

    public AElseParte(
        @SuppressWarnings("hiding") TSenao _senao_,
        @SuppressWarnings("hiding") List<?> _comandoPtVirg_)
    {
        // Constructor
        setSenao(_senao_);

        setComandoPtVirg(_comandoPtVirg_);

    }

    @Override
    public Object clone()
    {
        return new AElseParte(
            cloneNode(this._senao_),
            cloneList(this._comandoPtVirg_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAElseParte(this);
    }

    public TSenao getSenao()
    {
        return this._senao_;
    }

    public void setSenao(TSenao node)
    {
        if(this._senao_ != null)
        {
            this._senao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._senao_ = node;
    }

    public LinkedList<PComandoPtVirg> getComandoPtVirg()
    {
        return this._comandoPtVirg_;
    }

    public void setComandoPtVirg(List<?> list)
    {
        for(PComandoPtVirg e : this._comandoPtVirg_)
        {
            e.parent(null);
        }
        this._comandoPtVirg_.clear();

        for(Object obj_e : list)
        {
            PComandoPtVirg e = (PComandoPtVirg) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._comandoPtVirg_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._senao_)
            + toString(this._comandoPtVirg_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._senao_ == child)
        {
            this._senao_ = null;
            return;
        }

        if(this._comandoPtVirg_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._senao_ == oldChild)
        {
            setSenao((TSenao) newChild);
            return;
        }

        for(ListIterator<PComandoPtVirg> i = this._comandoPtVirg_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PComandoPtVirg) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
