/* This file was generated by SableCC (http://www.sablecc.org/). */

package portugol.node;

import java.util.*;
import portugol.analysis.*;

@SuppressWarnings("nls")
public final class AEscrevaExpLogicaComando extends PComando
{
    private final LinkedList<PExpLogica> _expLogica_ = new LinkedList<PExpLogica>();

    public AEscrevaExpLogicaComando()
    {
        // Constructor
    }

    public AEscrevaExpLogicaComando(
        @SuppressWarnings("hiding") List<?> _expLogica_)
    {
        // Constructor
        setExpLogica(_expLogica_);

    }

    @Override
    public Object clone()
    {
        return new AEscrevaExpLogicaComando(
            cloneList(this._expLogica_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAEscrevaExpLogicaComando(this);
    }

    public LinkedList<PExpLogica> getExpLogica()
    {
        return this._expLogica_;
    }

    public void setExpLogica(List<?> list)
    {
        for(PExpLogica e : this._expLogica_)
        {
            e.parent(null);
        }
        this._expLogica_.clear();

        for(Object obj_e : list)
        {
            PExpLogica e = (PExpLogica) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._expLogica_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expLogica_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expLogica_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        for(ListIterator<PExpLogica> i = this._expLogica_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PExpLogica) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
