/* This file was generated by SableCC (http://www.sablecc.org/). */

package portugol.node;

import portugol.analysis.*;

@SuppressWarnings("nls")
public final class AExpMultIgualExpIgual extends PExpIgual
{
    private PExpMultIgual _expMultIgual_;

    public AExpMultIgualExpIgual()
    {
        // Constructor
    }

    public AExpMultIgualExpIgual(
        @SuppressWarnings("hiding") PExpMultIgual _expMultIgual_)
    {
        // Constructor
        setExpMultIgual(_expMultIgual_);

    }

    @Override
    public Object clone()
    {
        return new AExpMultIgualExpIgual(
            cloneNode(this._expMultIgual_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExpMultIgualExpIgual(this);
    }

    public PExpMultIgual getExpMultIgual()
    {
        return this._expMultIgual_;
    }

    public void setExpMultIgual(PExpMultIgual node)
    {
        if(this._expMultIgual_ != null)
        {
            this._expMultIgual_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expMultIgual_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expMultIgual_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expMultIgual_ == child)
        {
            this._expMultIgual_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expMultIgual_ == oldChild)
        {
            setExpMultIgual((PExpMultIgual) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
