/* This file was generated by SableCC (http://www.sablecc.org/). */

package portugol.node;

import portugol.analysis.*;

@SuppressWarnings("nls")
public final class AExpParentes extends PExpParentes
{
    private TAbreParantes _abreParantes_;
    private PExpLogica _expLogica_;
    private TFechaParentes _fechaParentes_;

    public AExpParentes()
    {
        // Constructor
    }

    public AExpParentes(
        @SuppressWarnings("hiding") TAbreParantes _abreParantes_,
        @SuppressWarnings("hiding") PExpLogica _expLogica_,
        @SuppressWarnings("hiding") TFechaParentes _fechaParentes_)
    {
        // Constructor
        setAbreParantes(_abreParantes_);

        setExpLogica(_expLogica_);

        setFechaParentes(_fechaParentes_);

    }

    @Override
    public Object clone()
    {
        return new AExpParentes(
            cloneNode(this._abreParantes_),
            cloneNode(this._expLogica_),
            cloneNode(this._fechaParentes_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExpParentes(this);
    }

    public TAbreParantes getAbreParantes()
    {
        return this._abreParantes_;
    }

    public void setAbreParantes(TAbreParantes node)
    {
        if(this._abreParantes_ != null)
        {
            this._abreParantes_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._abreParantes_ = node;
    }

    public PExpLogica getExpLogica()
    {
        return this._expLogica_;
    }

    public void setExpLogica(PExpLogica node)
    {
        if(this._expLogica_ != null)
        {
            this._expLogica_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expLogica_ = node;
    }

    public TFechaParentes getFechaParentes()
    {
        return this._fechaParentes_;
    }

    public void setFechaParentes(TFechaParentes node)
    {
        if(this._fechaParentes_ != null)
        {
            this._fechaParentes_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._fechaParentes_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._abreParantes_)
            + toString(this._expLogica_)
            + toString(this._fechaParentes_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._abreParantes_ == child)
        {
            this._abreParantes_ = null;
            return;
        }

        if(this._expLogica_ == child)
        {
            this._expLogica_ = null;
            return;
        }

        if(this._fechaParentes_ == child)
        {
            this._fechaParentes_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._abreParantes_ == oldChild)
        {
            setAbreParantes((TAbreParantes) newChild);
            return;
        }

        if(this._expLogica_ == oldChild)
        {
            setExpLogica((PExpLogica) newChild);
            return;
        }

        if(this._fechaParentes_ == oldChild)
        {
            setFechaParentes((TFechaParentes) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
