/* This file was generated by SableCC (http://www.sablecc.org/). */

package portugol.node;

import portugol.analysis.*;

@SuppressWarnings("nls")
public final class AExpGlobalParentesFator extends PFator
{
    private TAbreParantes _abreParantes_;
    private PExpGlobal _expGlobal_;
    private TFechaParentes _fechaParentes_;

    public AExpGlobalParentesFator()
    {
        // Constructor
    }

    public AExpGlobalParentesFator(
        @SuppressWarnings("hiding") TAbreParantes _abreParantes_,
        @SuppressWarnings("hiding") PExpGlobal _expGlobal_,
        @SuppressWarnings("hiding") TFechaParentes _fechaParentes_)
    {
        // Constructor
        setAbreParantes(_abreParantes_);

        setExpGlobal(_expGlobal_);

        setFechaParentes(_fechaParentes_);

    }

    @Override
    public Object clone()
    {
        return new AExpGlobalParentesFator(
            cloneNode(this._abreParantes_),
            cloneNode(this._expGlobal_),
            cloneNode(this._fechaParentes_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExpGlobalParentesFator(this);
    }

    public TAbreParantes getAbreParantes()
    {
        return this._abreParantes_;
    }

    public void setAbreParantes(TAbreParantes node)
    {
        if(this._abreParantes_ != null)
        {
            this._abreParantes_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._abreParantes_ = node;
    }

    public PExpGlobal getExpGlobal()
    {
        return this._expGlobal_;
    }

    public void setExpGlobal(PExpGlobal node)
    {
        if(this._expGlobal_ != null)
        {
            this._expGlobal_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expGlobal_ = node;
    }

    public TFechaParentes getFechaParentes()
    {
        return this._fechaParentes_;
    }

    public void setFechaParentes(TFechaParentes node)
    {
        if(this._fechaParentes_ != null)
        {
            this._fechaParentes_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._fechaParentes_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._abreParantes_)
            + toString(this._expGlobal_)
            + toString(this._fechaParentes_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._abreParantes_ == child)
        {
            this._abreParantes_ = null;
            return;
        }

        if(this._expGlobal_ == child)
        {
            this._expGlobal_ = null;
            return;
        }

        if(this._fechaParentes_ == child)
        {
            this._fechaParentes_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._abreParantes_ == oldChild)
        {
            setAbreParantes((TAbreParantes) newChild);
            return;
        }

        if(this._expGlobal_ == oldChild)
        {
            setExpGlobal((PExpGlobal) newChild);
            return;
        }

        if(this._fechaParentes_ == oldChild)
        {
            setFechaParentes((TFechaParentes) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
