/* This file was generated by SableCC (http://www.sablecc.org/). */

package portugol.node;

import portugol.analysis.*;

@SuppressWarnings("nls")
public final class AExpParentesExpNao extends PExpNao
{
    private PExpParentes _expParentes_;

    public AExpParentesExpNao()
    {
        // Constructor
    }

    public AExpParentesExpNao(
        @SuppressWarnings("hiding") PExpParentes _expParentes_)
    {
        // Constructor
        setExpParentes(_expParentes_);

    }

    @Override
    public Object clone()
    {
        return new AExpParentesExpNao(
            cloneNode(this._expParentes_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExpParentesExpNao(this);
    }

    public PExpParentes getExpParentes()
    {
        return this._expParentes_;
    }

    public void setExpParentes(PExpParentes node)
    {
        if(this._expParentes_ != null)
        {
            this._expParentes_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expParentes_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expParentes_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expParentes_ == child)
        {
            this._expParentes_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expParentes_ == oldChild)
        {
            setExpParentes((PExpParentes) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
