/* This file was generated by SableCC (http://www.sablecc.org/). */

package portugol.node;

import portugol.analysis.*;

@SuppressWarnings("nls")
public final class AExpVirgula extends PExpVirgula
{
    private PExpGlobal _expGlobal_;
    private TVirgula _virgula_;

    public AExpVirgula()
    {
        // Constructor
    }

    public AExpVirgula(
        @SuppressWarnings("hiding") PExpGlobal _expGlobal_,
        @SuppressWarnings("hiding") TVirgula _virgula_)
    {
        // Constructor
        setExpGlobal(_expGlobal_);

        setVirgula(_virgula_);

    }

    @Override
    public Object clone()
    {
        return new AExpVirgula(
            cloneNode(this._expGlobal_),
            cloneNode(this._virgula_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExpVirgula(this);
    }

    public PExpGlobal getExpGlobal()
    {
        return this._expGlobal_;
    }

    public void setExpGlobal(PExpGlobal node)
    {
        if(this._expGlobal_ != null)
        {
            this._expGlobal_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expGlobal_ = node;
    }

    public TVirgula getVirgula()
    {
        return this._virgula_;
    }

    public void setVirgula(TVirgula node)
    {
        if(this._virgula_ != null)
        {
            this._virgula_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._virgula_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expGlobal_)
            + toString(this._virgula_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expGlobal_ == child)
        {
            this._expGlobal_ = null;
            return;
        }

        if(this._virgula_ == child)
        {
            this._virgula_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expGlobal_ == oldChild)
        {
            setExpGlobal((PExpGlobal) newChild);
            return;
        }

        if(this._virgula_ == oldChild)
        {
            setVirgula((TVirgula) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
