/* This file was generated by SableCC (http://www.sablecc.org/). */

package portugol.node;

import java.util.*;
import portugol.analysis.*;

@SuppressWarnings("nls")
public final class ALeiaComando extends PComando
{
    private final LinkedList<PVariavel> _variavel_ = new LinkedList<PVariavel>();

    public ALeiaComando()
    {
        // Constructor
    }

    public ALeiaComando(
        @SuppressWarnings("hiding") List<?> _variavel_)
    {
        // Constructor
        setVariavel(_variavel_);

    }

    @Override
    public Object clone()
    {
        return new ALeiaComando(
            cloneList(this._variavel_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseALeiaComando(this);
    }

    public LinkedList<PVariavel> getVariavel()
    {
        return this._variavel_;
    }

    public void setVariavel(List<?> list)
    {
        for(PVariavel e : this._variavel_)
        {
            e.parent(null);
        }
        this._variavel_.clear();

        for(Object obj_e : list)
        {
            PVariavel e = (PVariavel) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._variavel_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._variavel_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._variavel_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        for(ListIterator<PVariavel> i = this._variavel_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PVariavel) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
