/* This file was generated by SableCC (http://www.sablecc.org/). */

package portugol.node;

import portugol.analysis.*;

@SuppressWarnings("nls")
public final class AMenosExpGlobalExpGlobal extends PExpGlobal
{
    private TMenos _menos_;
    private PExpGlobal _expGlobal_;

    public AMenosExpGlobalExpGlobal()
    {
        // Constructor
    }

    public AMenosExpGlobalExpGlobal(
        @SuppressWarnings("hiding") TMenos _menos_,
        @SuppressWarnings("hiding") PExpGlobal _expGlobal_)
    {
        // Constructor
        setMenos(_menos_);

        setExpGlobal(_expGlobal_);

    }

    @Override
    public Object clone()
    {
        return new AMenosExpGlobalExpGlobal(
            cloneNode(this._menos_),
            cloneNode(this._expGlobal_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMenosExpGlobalExpGlobal(this);
    }

    public TMenos getMenos()
    {
        return this._menos_;
    }

    public void setMenos(TMenos node)
    {
        if(this._menos_ != null)
        {
            this._menos_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._menos_ = node;
    }

    public PExpGlobal getExpGlobal()
    {
        return this._expGlobal_;
    }

    public void setExpGlobal(PExpGlobal node)
    {
        if(this._expGlobal_ != null)
        {
            this._expGlobal_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expGlobal_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._menos_)
            + toString(this._expGlobal_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._menos_ == child)
        {
            this._menos_ = null;
            return;
        }

        if(this._expGlobal_ == child)
        {
            this._expGlobal_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._menos_ == oldChild)
        {
            setMenos((TMenos) newChild);
            return;
        }

        if(this._expGlobal_ == oldChild)
        {
            setExpGlobal((PExpGlobal) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
