/* This file was generated by SableCC (http://www.sablecc.org/). */

package portugol.node;

import portugol.analysis.*;

@SuppressWarnings("nls")
public final class AOuExpOu extends PExpOu
{
    private PExpOu _expOu_;
    private TOu _ou_;
    private PExpE _expE_;

    public AOuExpOu()
    {
        // Constructor
    }

    public AOuExpOu(
        @SuppressWarnings("hiding") PExpOu _expOu_,
        @SuppressWarnings("hiding") TOu _ou_,
        @SuppressWarnings("hiding") PExpE _expE_)
    {
        // Constructor
        setExpOu(_expOu_);

        setOu(_ou_);

        setExpE(_expE_);

    }

    @Override
    public Object clone()
    {
        return new AOuExpOu(
            cloneNode(this._expOu_),
            cloneNode(this._ou_),
            cloneNode(this._expE_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAOuExpOu(this);
    }

    public PExpOu getExpOu()
    {
        return this._expOu_;
    }

    public void setExpOu(PExpOu node)
    {
        if(this._expOu_ != null)
        {
            this._expOu_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expOu_ = node;
    }

    public TOu getOu()
    {
        return this._ou_;
    }

    public void setOu(TOu node)
    {
        if(this._ou_ != null)
        {
            this._ou_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._ou_ = node;
    }

    public PExpE getExpE()
    {
        return this._expE_;
    }

    public void setExpE(PExpE node)
    {
        if(this._expE_ != null)
        {
            this._expE_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expE_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expOu_)
            + toString(this._ou_)
            + toString(this._expE_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expOu_ == child)
        {
            this._expOu_ = null;
            return;
        }

        if(this._ou_ == child)
        {
            this._ou_ = null;
            return;
        }

        if(this._expE_ == child)
        {
            this._expE_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expOu_ == oldChild)
        {
            setExpOu((PExpOu) newChild);
            return;
        }

        if(this._ou_ == oldChild)
        {
            setOu((TOu) newChild);
            return;
        }

        if(this._expE_ == oldChild)
        {
            setExpE((PExpE) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
