/* This file was generated by SableCC (http://www.sablecc.org/). */

package portugol.node;

import portugol.analysis.*;

@SuppressWarnings("nls")
public final class APasso extends PPasso
{
    private TPasso _passo_;
    private TNumInt _numInt_;

    public APasso()
    {
        // Constructor
    }

    public APasso(
        @SuppressWarnings("hiding") TPasso _passo_,
        @SuppressWarnings("hiding") TNumInt _numInt_)
    {
        // Constructor
        setPasso(_passo_);

        setNumInt(_numInt_);

    }

    @Override
    public Object clone()
    {
        return new APasso(
            cloneNode(this._passo_),
            cloneNode(this._numInt_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPasso(this);
    }

    public TPasso getPasso()
    {
        return this._passo_;
    }

    public void setPasso(TPasso node)
    {
        if(this._passo_ != null)
        {
            this._passo_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._passo_ = node;
    }

    public TNumInt getNumInt()
    {
        return this._numInt_;
    }

    public void setNumInt(TNumInt node)
    {
        if(this._numInt_ != null)
        {
            this._numInt_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._numInt_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._passo_)
            + toString(this._numInt_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._passo_ == child)
        {
            this._passo_ = null;
            return;
        }

        if(this._numInt_ == child)
        {
            this._numInt_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._passo_ == oldChild)
        {
            setPasso((TPasso) newChild);
            return;
        }

        if(this._numInt_ == oldChild)
        {
            setNumInt((TNumInt) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
