/* This file was generated by SableCC (http://www.sablecc.org/). */

package portugol.analysis;

import portugol.node.*;

public interface Analysis extends Switch
{
    Object getIn(Node node);
    void setIn(Node node, Object o);
    Object getOut(Node node);
    void setOut(Node node, Object o);

    void caseTPrograma(TPrograma node);
    void caseTInicio(TInicio node);
    void caseTFim(TFim node);
    void caseTConst(TConst node);
    void caseTVar(TVar node);
    void caseTEscreva(TEscreva node);
    void caseTLeia(TLeia node);
    void caseTInteiro(TInteiro node);
    void caseTReal(TReal node);
    void caseTCaractere(TCaractere node);
    void caseTDiv(TDiv node);
    void caseTSe(TSe node);
    void caseTEntao(TEntao node);
    void caseTFimSe(TFimSe node);
    void caseTAvalie(TAvalie node);
    void caseTCaso(TCaso node);
    void caseTFimAvalie(TFimAvalie node);
    void caseTSenao(TSenao node);
    void caseTFaca(TFaca node);
    void caseTAte(TAte node);
    void caseTEnquanto(TEnquanto node);
    void caseTFimEnquanto(TFimEnquanto node);
    void caseTRepita(TRepita node);
    void caseTPara(TPara node);
    void caseTDe(TDe node);
    void caseTPasso(TPasso node);
    void caseTPare(TPare node);
    void caseTContinue(TContinue node);
    void caseTFimPara(TFimPara node);
    void caseTMais(TMais node);
    void caseTMenos(TMenos node);
    void caseTProduto(TProduto node);
    void caseTDivisao(TDivisao node);
    void caseTIncremento(TIncremento node);
    void caseTDecremento(TDecremento node);
    void caseTAtribuicao(TAtribuicao node);
    void caseTVirgula(TVirgula node);
    void caseTDoisPts(TDoisPts node);
    void caseTPtVirg(TPtVirg node);
    void caseTAbreParantes(TAbreParantes node);
    void caseTFechaParentes(TFechaParentes node);
    void caseTAbreColchete(TAbreColchete node);
    void caseTFechaColchete(TFechaColchete node);
    void caseTAspasSp(TAspasSp node);
    void caseTXor(TXor node);
    void caseTOu(TOu node);
    void caseTNao(TNao node);
    void caseTE(TE node);
    void caseTIgual(TIgual node);
    void caseTDiferente(TDiferente node);
    void caseTMaior(TMaior node);
    void caseTMenor(TMenor node);
    void caseTMaiorIgual(TMaiorIgual node);
    void caseTMenorIgual(TMenorIgual node);
    void caseTIdentificador(TIdentificador node);
    void caseTNumInt(TNumInt node);
    void caseTNumReal(TNumReal node);
    void caseTAllEspaco(TAllEspaco node);
    void caseTComentLinha(TComentLinha node);
    void caseTComentAninhado(TComentAninhado node);
    void caseTComentEscopo(TComentEscopo node);
    void caseTComentEstrela(TComentEstrela node);
    void caseTComentBarra(TComentBarra node);
    void caseTComentFim(TComentFim node);
    void caseEOF(EOF node);
    void caseInvalidToken(InvalidToken node);
}
